name: CoRA

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Code-Review-Assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Code Review Assistant
        uses: Tarik2508/GPT-Reviewer@Releases/v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_AI_SECRET_FOR_AI_CODE_REVIEW: ${{ secrets.OPEN_AI_SECRET_FOR_AI_CODE_REVIEW }}
